//  Data from Housing,houssed,vital,99
import Empirien from '../assets/Empirien.jpg'

 const residentialProjects = [
    {
      id: 1,
      title: "Shivalik Avenue",
      subtitle: "Modern Urban Living",
      category: "Residential",
      details: ["3 BHK", "1500 sqft", "Ahmedabad"],
      bg:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3',
      locality:'Bodakdev, Ahmedabad',
      area:'Bodakdev | Ready to move',
      bt1:'Apartment',
      bt2:'Buy',
      bt3:'Invest',
      images : [
       'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3',
       'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?ixlib=rb-4.0.3',
       'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3',
      ],
      segment:"Luxury",
      address:'Shivalik Avenue, Near Nirma Vidya Vihar School, Bodakdev Fire Station Road, Bodakdev, Ahmedabad 380054',
      bhk:"4 BHK",
      build:"3270 - 3275 Sq Ft",
      price :'₹ 2.4 Cr - 2.45 Cr',
      possession:'Ready to Move',
      nou:'121 Units',
      rera : "PR/GJ/AHMEDABAD/AHMEDABAD CI TY/AUDA/MAA02517/260418",
      developer:'Shivalik Group',
      ptype:'Apartment',
      parea:'1.26 Acres',
      ownership:'Freehold',
      not:'1 Towers',
      nof:'7 Floors',
      parking:'Two Wheeler, Four Wheeler',
      overviewpara1:'Shivalik Avenue is one of the finest buildings built by the renowned Shivalik House in Ahmedabad. This property is a perfect blend of classy designs with a fusion of vision and thoughts that add convenience.',
      overviewpara2:'The project is crafted with the addition of technology and aesthetic touch. This place is a perfect destination to live your life how you want. It is a place for those individuals who wish to experience a rejuvenating experience with lifetime scenic views. Surrounded by a friendly neighborhood and many landmark places such as Bharat Petrol Pump, Bodakdev Police Station, Nirma Vidyamandir, The Grand Bhagwati, IDBI Bank, and for free travelers SG Highway.',
      floorimg:'https://houssed.com/Assets/Files/Projects/1491/BHK_Configuration/1491_1678021504_8c303b82f90dc4958f8739feeea6444c.webp',
      video:'https://www.youtube.com/embed/QV9v6MGfcWs',
    },

    {
      id: 2,
      title: "The Empiirean",
      subtitle: "Living Above the Clouds",
      category: "Residential",
      details: ["4 BHK", "429 sq-yrd", "Ahmedabad"],
      bg:'https://housing-images.n7net.in/012c1500/6251bb854ca906d6a4064d07d8da81b8/v0/fs.jpeg',
      locality:'Chharodi, Ahmedabaad.',
      area:'Chharodi | Under Construction ',
      bt1:'Apartment',
      bt2:'Buy',
      bt3:'Invest',
      images : [
        Empirien,
       'https://housing-images.n7net.in/4f2250e8/e7a14dc2deaa90c47ba6d7cfcac91cbd/v0/fs/the_empiirean-vaishno_devi_circle_ahmedabad-ahmedabad-ascent_sky_infracon_llp.jpeg',
       'https://housing-images.n7net.in/012c1500/6fff30cc69e193c21d7b20c78f79d1bd/v0/fs.jpeg',
       'https://housing-images.n7net.in/012c1500/ea9df2c2b3f70043dbd67991544f5802/v0/fs.jpeg'
      ],
      segment:"Luxury",
      address:'The Empiirean, Near Spinny, SG Highway, Chharodi, Ahmedabaad.',
      bhk:"4,5 BHK",
      build:"429 sq-yrd",
      price :'Price on Request',
      possession:'Under Construction',
      nou:'160',    
      developer:'Ascent Sky Infracon Llp',
      ptype:'Apartment',
      parea:'1.52 Acres',
      ownership:'Freehold',
      not:'2',
      nof:'21',
      parking:'Two Wheeler, Four Wheeler',
      overviewpara1:'Looking for Apartment in Chharodi, Ahmedabad?. The Empiirean is a project by Ascent Sky Infracon Llp. The project is offering 4 BHK, 5 BHK. It is set in 1.52 Acres . The Empiirean is a Under Construction residentialÂ  The Empiirean is located in Beside Swarnim Stone, Opp. Nirma University, Chharodi. The Empiirean was launched in May 2023.',
      overviewpara2:'The Empiirean offers a host of facilities for residents. These amenities in The Empiirean are those that every homebuyer aspires for!. Chharodi is well-connected to other parts of city by road, which passes through the heart of this suburb. Prominent shopping malls, movie theatres, school, and hospitals are present in proximity of this residential project.',
      floorimg1:'https://housing-images.n7net.in/012c1500/688bb6af0ca3ce3166b5e757a84d4507/v0/fs.jpeg',
      floorimg2:'https://housing-images.n7net.in/012c1500/26ab7764e3eea0058964330ebefd9a68/v0/fs.jpeg',
      floordata:'A,B-Block',
      video:'https://www.youtube.com/embed/nPjUbxQ9zcM',
      
    },

    {
      id: 3,
      title: "Shilp Skyline",
      subtitle: "Modern Urban Living",
      category: "Residential",
      details: ["4 BHK", "3071 Sq.ft.", "Ahmedabad"],
      bg:'https://skyline-ahmedabad.in/wp-content/uploads/qjwaedfbswakwjhdfbsqakj.webp',
      locality:'Vaishnodevi Circle, Ahmedabad',
      area:'Shantigram, Vaishnodevi Circle | Under Construction ',
      bt1:'Apartment',
      bt2:'Buy',
      bt3:'Invest',
      images : [
        'https://housing-images.n7net.in/012c1500/99f2cefd427bcca751262888bf4fca61/v0/fs.jpeg',
        'https://lh3.googleusercontent.com/p/AF1QipOMAbNqlS147HaLVLadia1pTzOlwcj3Bnq6SEic=s680-w680-h510',
       'https://lh3.googleusercontent.com/p/AF1QipP66pMjzS4WJqsyZtqFaF6U0FI1UBx7GTdZGYg5=s680-w680-h510',
       'https://housing-images.n7net.in/012c1500/101b8409e634f29960f171aea8e329d3/v0/fs.jpeg',
       'https://housing-images.n7net.in/012c1500/ec2b7acee5445732a71e80eb53ff6ccf/v0/fs-large.jpeg',
       
      ],
      segment:"Luxury",
      address:'Shilp Skyline, Near KD Hospital, Shanti Dham Road, Vaishnodevi Circle, Ahmedabad.',
      bhk:"4 BHK",
      build:"3071 Sq.ft.",
      price :'Price on Request',
      possession:'Under Construction',
      nou:'256',    
      developer:'Shilp Group',
      ptype:'Apartment',
      parea:'2.05 Acres',
      ownership:'Freehold',
      not:'1',
      nof:'21',
      parking:'Two Wheeler, Four Wheeler',
      overviewpara1:'Shilp Skyline, located in the prime area of Vaishnodevi Circle, offers an exceptional residential experience that blends comfort with luxury. This project is designed to cater to modern living needs, ensuring that each unit is a perfect combination of style and functionality. With a focus on delivering top-tier residential spaces, Shilp Skyline stands out as a symbol of contemporary elegance and refined architecture.',
      overviewpara2:'The project epitomizes luxury living, featuring world-class specifications and a wide range of amenities that elevate the overall lifestyle. Residents can enjoy facilities such as a well-equipped fitness center, landscaped gardens, childrens play areas, and more. These thoughtfully curated amenities ensure that the project meets the diverse requirements of its residents, providing both convenience and leisure in one place.',
      floorimg1:'https://c.housingcdn.com/demand/s/client/common/assets/requestFloorPlan.f9b9d5bc.jpg',
      floordata:'',
      floorimg2:'',
      video:"https://www.youtube.com/embed/ADbDrWvfnlk?si=tAfILRQ7y513sCnp",
      
    },
    
    {
      id: 4,
      title: "Aristo The Regal",
      subtitle: "Warm and Comfortable Living",
      category: "Residential",
      details: ["4 BHK", "335,347,431 Sq.yrd", "Ahmedabad"],
      bg:'https://www.aristobuilder.com/wp-content/uploads/2019/04/IMG_1617-1170x658.jpg',
      locality:'Vaishnodevi Circle, Ahmedabad',
      area:'Shantigram, Vaishnodevi Circle | Under Construction ',
      bt1:'Apartment',
      bt2:'Buy',
      bt3:'Invest',
      images : [
        'https://housing-images.n7net.in/4f2250e8/58ab2cebd975d47575beec44b24ebb0a/v0/fs/the_regal-vaishno_devi_circle_ahmedabad-ahmedabad-artham_ventures.jpeg',
        'https://www.aristobuilder.com/wp-content/uploads/2019/04/IMG_1611-1170x658.jpg',
        'https://www.aristobuilder.com/wp-content/uploads/2019/04/IMG_1616-1170x658.jpg',
        'https://www.aristobuilder.com/wp-content/uploads/2019/04/IMG_1615-1170x658.jpg',
        'https://www.aristobuilder.com/wp-content/uploads/2019/04/IMG_1620-1170x658.jpg',
      ],
      segment:"Luxury",
      address:'Aristo The Regal, B/H, Vaishnodevi Mandir Rd, Khoraj, Ahmedabad, Gujarat 382421',
      bhk:"4 BHK",
      build:"335,347,431 Sq.yrd",
      price :'Price on Request',
      possession:'Under Construction',
      nou:'103',    
      developer:'Aristo Builder',
      ptype:'Apartment',
      parea:'1.63 Acres',
      ownership:'Freehold',
      not:'3',
      nof:'21',
      parking:'Two Wheeler, Four Wheeler',
      overviewpara1:'Aristo The Regal is a prestigious residential project that offers an elevated living experience, designed for those who seek luxury and sophistication. Located in a prime area, Aristo The Regal offers spacious and meticulously crafted homes that cater to modern families. The project features well-designed 4 BHK apartments that provide ample natural light, ventilation, and space, ensuring maximum comfort and convenience for residents.',
      overviewpara2:'The development is equipped with a range of premium amenities, including a state-of-the-art fitness center, swimming pool, children’s play area, landscaped gardens, and more, ensuring a lifestyle that promotes both relaxation and recreation. The project’s focus on quality and attention to detail is evident in every aspect, from the architecture to the choice of materials used. Aristo The Regal also features world-class security systems, ensuring peace of mind for all its residents.',
      floorimg1:'https://houssed.com/Assets/Files/Projects//123114/Floor%20Plan/Fp-1733990708.webp',
      floordata:'',
      floorimg2:'',
      video:"https://www.youtube.com/embed/VXP8Btq1jhQ?si=GdjZYKT6CM05wRhq",
      
    },

    {
      id: 5,
      title: "Highline",
      subtitle: "A new name in luxury living",
      category: "Residential",
      details: ["3,4 BHK", "2700,3800 Sq.ft", "Ahmedabad"],
      bg:'https://www.theaggroup.in/assets/img/gallery/1_17.jpg',
      locality:'Vaishnodevi Circle, Ahmedabad',
      area:'Shantigram, Vaishnodevi Circle | Under Construction ',
      bt1:'Apartment',
      bt2:'Buy',
      bt3:'Invest',
      images : [
        'https://www.theaggroup.in/assets/img/3d-images-3-max.jpg',
        'https://www.theaggroup.in/assets/img/gallery/1_11.jpg',
        'https://www.theaggroup.in/assets/img/gallery/1_12.jpg',
        'https://www.theaggroup.in/assets/img/gallery/1_5.jpg',
        'https://www.theaggroup.in/assets/img/home-banner.jpg',
      ],
      segment:"Luxury",
      address:'New Science City Road, S.G Highway, North West, Ahmedabad',
      bhk:"3,4 BHK",
      build:"2700,3800 Sq.ft",
      price :'Price on Request',
      possession:'Under Construction',
      nou:'349',    
      developer:'Aristo Builder',
      ptype:'Apartment',
      parea:'1.63 Acres',
      ownership:'Freehold',
      not:'3',
      nof:'21',
      parking:'Two Wheeler, Four Wheeler',
      overviewpara1:'AG Highline Phase 1 stands as an epitome of contemporary living in the heart of a bustling city. This residential marvel is strategically positioned, enveloped by premier shopping and dining destinations, and surrounded by cultural and artsy landmarks. The architectural brilliance of AG Highline Phase 1 ensures not just a dwelling but a lifestyle statement that captivates the mind.',
      overviewpara2:'AG Highline Phase 1 boasts state-of-the-art amenities, elevating the living experience. The fourth feature highlights the seamless integration of modern technology for security and convenience.',
      floorimg1:'https://housing-images.n7net.in/91aba65c/a28f4d78ae9a7622b1bb16967e6b164b/v0/fs-large.png',
      floordata:'',
      floorimg2:'',
      video:"https://www.youtube.com/embed/fuYjh2yVdYI?si=Z5Phpp16IFDU6ddd",
    },

    {
      id: 6,
      title: "Adani Amogha",
      subtitle: "Apartments Amidst Greenscapes",
      category: "Residential",
      details: ["3 BHK", "1500 Sq.ft", "Ahmedabad"],
      bg:'https://www.adanirealty.com/-/media/project/realty/residential/ahmedabad/amogha/carousel-images/outdoor/amogha_cover-image.ashx',
      locality:'Near Vaishnodevi Circle On SG Highway, Ahmedabad',
      area:'Shantigram Vaishnodevi Circle | Ready To Move ',
      bt1:'Apartment',
      bt2:'Buy',
      bt3:'Invest',
      images : [
        'https://www.adanirealty.com/-/media/project/realty/residential/ahmedabad/amogha/carousel-images/1920x1080/1920x1080-amogha-07.ashx',
        'https://www.adanirealty.com/-/media/project/realty/residential/ahmedabad/amogha/carousel-images/outdoor/amogha_01.ashx',
        'https://www.adanirealty.com/-/media/project/realty/residential/ahmedabad/amogha/carousel-images/1920x1080/1920x1080-amogha-06.ashx',
        'https://www.adanirealty.com/-/media/project/realty/residential/ahmedabad/amogha/carousel-images/outdoor/amogha_04.ashx',
        'https://www.adanirealty.com/-/media/project/realty/residential/ahmedabad/amogha/carousel-images/outdoor/amogha_07.ashx',
        'https://www.adanirealty.com/-/media/project/realty/residential/ahmedabad/amogha/carousel-images/1920x1080/1920x1080-amogha-02.ashx',
      ],
      segment:"Luxury",
      address:'Adani Amogha, Near Adani University, Shantigram Road, Shantigram, Ahmedabad 382421',
      bhk:"3 BHK",
      build:"1500 Sq.ft",
      price :'Price on Request',
      possession:'Ready To Move',
      nou:'200',    
      developer:'Adani Realty',
      ptype:'Apartment',
      parea:'3.42 Acres',
      ownership:'Freehold',
      not:'8',
      nof:'14',
      parking:'Two Wheeler, Four Wheeler',
      overviewpara1:'Adani Amogha, developed by Adani Realty in Ahmedabad, is a distinguished residential project that exemplifies modern living with a focus on comfort and sustainability. This development offers a variety of meticulously designed apartments that cater to diverse family needs, providing spacious layouts and contemporary finishes.',
      overviewpara2:'The project is thoughtfully crafted to promote a balanced lifestyle, featuring a range of amenities that enhance community living. Located in a prime area, Adani Amogha ensures residents have easy access to essential amenities, educational institutions, and transportation networks',
      floorimg1:'https://www.adanirealty.com/-/media/project/realty/residential/ahmedabad/amogha/layouts/floor-plans/amogha_floor_plan.ashx',
      floordata:'3 BHK',
      floorimg2:'',
      video:"https://www.youtube.com/embed/Gn4N-daZtX4?si=t1W6-fmQj3CLmc0Z",
    },

    {
      id: 7,
      title: "Aavishkar Atlantis Elevate",
      subtitle: "Perfect Homes for Families",
      category: "Residential",
      details: ["3 BHK", "2250,2610 sq.ft.", "Ahmedabad"],
      bg:'https://housing-images.n7net.in/4f2250e8/809d946b353fcb48fe5d5c8a049bd015/v0/fs/aavishkar_atlantis_elevate-vaishno_devi_circle_ahmedabad-ahmedabad-aavishkar_realty.jpeg',
      locality:'Near Vaishnodevi Circle On SG Highway, Ahmedabad',
      area:'Vaishnodevi Circle | Under Construction ',
      bt1:'Apartment',
      bt2:'Buy',
      bt3:'Invest',
      images : [
        'https://housing-images.n7net.in/012c1500/6ec3417428a73743a97809a034bff396/v0/fs.jpeg',
        'https://housing-images.n7net.in/012c1500/03398c942fc120ca84573e742915a276/v0/fs.jpeg',
        'https://housing-images.n7net.in/012c1500/fc47fa5da2aaf43ff53037080a2bce07/v0/fs.jpeg',
        'https://housing-images.n7net.in/012c1500/a8143390bdf9b9e8da869837ad6f409f/v0/fs.jpeg',
        'https://housing-images.n7net.in/012c1500/70736949f5bb3e00c6aa165be0c1be6b/v0/fs.jpeg',
      ],
      segment:"Luxury",
      address:'Atlantis Elevate Vaishnodevi Circle, Nr Ratna Paradise, Service Road Vaishnodevi Zundal Underpass, Tragad, North West, Ahmedabad',
      bhk:"3 BHK",
      build:"2250,2610 sq.ft.",
      price :'Price on Request',
      possession:'Under Constructione',
      nou:'90',    
      developer:'Aavishkar Realty',
      ptype:'Apartment',
      parea:'0.72 Acres',
      ownership:'Freehold',
      not:'3',
      nof:'14',
      parking:'Two Wheeler, Four Wheeler',
      overviewpara1:'For those looking to buy a residential property, here comes one of the choicest offerings in Ahmedabad North, at Vaishnodevi Circle. Brought to you by Aavishkar Properties, Aavishkar Atlantis Elevate is among the newest addresses for homebuyers. This is a new launch project right now, and is expected to be delivered by Mar, 2027. It has a variety of options to choose from that too in a varied budget range.',
      overviewpara2:'Aavishkar Properties is one of the known real estate brands in Ahmedabad North. Around 1 project is upcoming.',
      floorimg1:'https://www.adanirealty.com/-/media/project/realty/residential/ahmedabad/amogha/layouts/floor-plans/amogha_floor_plan.ashx',
      floordata:'3 BHK',
      floorimg2:'',
      video:"https://www.youtube.com/embed/Gn4N-daZtX4?si=t1W6-fmQj3CLmc0Z",
    },

    {
      id: 8,
      title: "Samatva Magnolia",
      subtitle: "we bring together modern living and nature",
      category: "Residential",
      details: ["3 BHK", "2079-2475 sq.ft.", "Ahmedabad"],
      bg:'https://lh3.googleusercontent.com/p/AF1QipOlDVJxeU9vSR_pm5gAjaLHuWhGBoS0wZSZ-SfO=s680-w680-h510',
      locality:'Ognaj, Ahmedabad, Gujarat 380060',
      area:'Ognaj | Under Construction ',
      bt1:'Apartment',
      bt2:'Buy',
      bt3:'Invest',
      images : [
        'https://lh3.googleusercontent.com/p/AF1QipNkBUDYwvlBOkQib59MDxSNTEjhoq3Kpxp7qfuD=s680-w680-h510',
        'https://lh3.googleusercontent.com/p/AF1QipN3PW8UXBVQF1yO4wPD_vrzTSJ89je4SjCrMevA=s680-w680-h510',
        'https://lh3.googleusercontent.com/p/AF1QipNuA58j4A3V6rulscv7Hs4orfOcv4jq6gE8Avnb=s680-w680-h510',
        'https://lh3.googleusercontent.com/p/AF1QipPFKl9z5ou1czg94DiYII7M8OWzTrp9jQdIdu0V=s680-w680-h510',
        'https://lh3.googleusercontent.com/p/AF1QipNSsLSupKl0_OSF4su6qsaWNrCdHpd7_EOM0uCa=s680-w680-h510',
      ],
      segment:"Luxury",
      address:'Samatva Magnolia 132 Ft New Ognaj-Gota Road, Ognaj, North West, Ahmedabad',
      bhk:"3 BHK",
      build:"2079-2475 sq.ft.",
      price :'Price on Request',
      possession:'Under Constructione',
      nou:'339',    
      developer:'Samatva Group',
      ptype:'Apartment',
      parea:'2.42 Acres',
      ownership:'Freehold',
      not:'7',
      nof:'14',
      parking:'Two Wheeler, Four Wheeler',
      overviewpara1:'Samatva Group is one of the known real estate brands in Ahmedabad West.  There is 1 project of this builder, which is currently under-construction.',
      overviewpara2:'Check out Samatva Magnolia in Ognaj , one of the upcoming under-construction housing societies in Ahmedabad West. There are apartments for sale in Samatva Magnolia Ognaj , SG Highway. This society will have all basic facilities and amenities to suit homebuyer’s needs and requirements.  Brought to you by Samatva Group.',
      floorimg1:'https://housing-images.n7net.in/012c1500/2a67927cc0c3407a13eb80279870c3b7/v0/fs.jpeg',
      floordata:'2ND TO 13TH',
      floorimg2:'',
      video:"https://www.youtube.com/embed/WdMm-oggB4A?si=Kxn5kF_Z2Jsu30zc",
    },

    {
      id: 9,
      title: "Aristo Anandam",
      subtitle: "Green Living for Modern Families",
      category: "Residential",
      details: ["3 BHK", "1755,1836 sq.ft.", "Ahmedabad"],
      bg:'https://lh3.googleusercontent.com/p/AF1QipO4mXzzdToSGJqqSCxOZQHFDdipF64zBqv_78hW=s680-w680-h510',
      locality:'Vaishnodevi Circle, Ahmedabad',
      area:'Vaishnodevi Circle | Ready To Move ',
      bt1:'Apartment',
      bt2:'Buy',
      bt3:'Invest',
      images : [
        'https://lh3.googleusercontent.com/p/AF1QipPBW0KZPdXgdGT4NfFOPYf4HgqHXrk__2qO2S6g=s680-w680-h510',
        'https://lh3.googleusercontent.com/p/AF1QipPIrfXGf0YF3K_TbLccHSZk8jXCiGM197A1IfS3=s680-w680-h510',
        'https://lh3.googleusercontent.com/p/AF1QipPzNUx0lYQ5JWDOubP7_5Ef_pwyyBaaWAmWkWId=s680-w680-h510',
        'https://lh3.googleusercontent.com/p/AF1QipN1hqQmJHzIlLZYtGoAh8_lV3LPn83RdNu-hPKZ=s680-w680-h510',
        'https://lh3.googleusercontent.com/p/AF1QipMSb5QOoYrhY4ZJgN9IhWUNUG1buumXELoEJVmW=s680-w680-h510',
      ],
      segment:"Affordable",
      address:'Aristo Anandam, near Malabar Exotica Road, behind NIRMA UNIVERSITY, Ahmedabad, Gujarat 382470',
      bhk:"3 BHK",
      build:"1755,1836 sq.ft.",
      price :'Price on Request',
      possession:'Ready To Move',
      nou:'216',    
      developer:'Aristo Builder',
      ptype:'Apartment',
      parea:'1.33 Acres',
      ownership:'Freehold',
      not:'4',
      nof:'14',
      parking:'Two Wheeler, Four Wheeler',
      overviewpara1:'The grace of a structure in upscaling your life, the modern designs to make you imagine you are in the future. Introducing Aristo Anandam, a stunning property that is a treat to your eyes. The property is a perfect blend of luxury and modern infrastructure.',
      overviewpara2:'The grand entrance, a swimming pool, a well-equipped gymnasium, a parking lot, and many more such high-end amenities make you feel you are at the right place. The best part of this property is the surrounding of the property, and the great green space from your balcony makes your day perfect.',
      floorimg1:'https://housing-images.n7net.in/91aba65c/90cacf01ba5f26ea03db1f64f7d7ba5a/v0/fs.jpeg',
      floordata:'A,B Block',
      floorimg2:'https://housing-images.n7net.in/91aba65c/ad40d8d1ae3355c29575defe8816c494/v0/fs.jpeg',
      video:"https://www.youtube.com/embed/2fvqZWUsMOc?si=Gzh1msPYAgww6vF8",
    },

    {
      id: 10,
      title: "Signor Skyline",
      subtitle: "Projects offering modern amenities and luxury living",
      category: "Residential",
      details: ["3 BHK", "1845 sq.ft.", "Ahmedabad"],
      bg:'https://lh3.googleusercontent.com/p/AF1QipPrAQbs1x3FQD7LNGjZqocD6HBUTEz_fCaySYGF=s680-w680-h510',
      locality:'Zundal, North West, Ahmedabad',
      area:'Zundal | Ready To Move ',
      bt1:'Apartment',
      bt2:'Buy',
      bt3:'Invest',
      images : [
        'https://lh3.googleusercontent.com/p/AF1QipP6-CBntoUxl516AEux06ZBpO26lcuvgNAD5OYE=s680-w680-h510',
        'https://lh3.googleusercontent.com/p/AF1QipNNdZ2xaHqPHeMIcOzyAVk4YBhsoJB4J8LjDz43=s680-w680-h510',
        'https://lh3.googleusercontent.com/p/AF1QipNNj7wAZJ5g4SFMePPmgPyCLw7JaJbJHsXMKPig=s680-w680-h510',
        'https://lh3.googleusercontent.com/p/AF1QipMI5WaMOGZAgFasYb639bE1RzEcPniyQp1R709R=s680-w680-h510',
      ],
      segment:"Affordable",
      address:'Signor Skyline, Opp. CBD Mall, Nr. Pushakar Residency, B/H. Vivaan infinity, Zundal, North West, Ahmedabad',
      bhk:"3 BHK",
      build:"1845 sq.ft.",
      price :'Price on Request',
      possession:'Ready To Move',
      nou:'237',    
      developer:'SAMARPAN DEVELOPERS',
      ptype:'Apartment',
      parea:'1.35 Acres',
      ownership:'Freehold',
      not:'4',
      nof:'14',
      parking:'Two Wheeler, Four Wheeler',
      overviewpara1:'Samarpan Signor Skyline by Samarpan Developers in Zundal is a premier real estate offering that epitomizes opulent living. These 3 BHK homes boast a magnificent structure and are designed to provide a luxurious lifestyle. The project features a variety of modern amenities, ensuring a high standard of living for its residents.',
      overviewpara2:'The development includes a party lawn, gym, multipurpose court/hall, indoor games area, and a library. These facilities cater to the diverse needs of residents, promoting a vibrant community life. The green landscape is complemented by an Acupressure Pathway, enhancing the overall wellness experience. This emphasis on lifestyle and nature creates a serene and invigorating environment.',
      floorimg1:'https://houssed.com/Assets/Files/Projects/11516/Floor%20Plan/985eb9ad3b25c7231ca2e14e3e88f08b.webp',
      floordata:'A Block',
      floorimg2:'',
      video:"https://www.youtube.com/embed/EcP-ipEd6gU?si=nknqS4NceBPqvWVb",
    },

    {
      id: 11,
      title: "The Atlantis 2",
      subtitle: "Projects offering modern amenities and luxury living",
      category: "Residential",
      details: ["3 BHK", "1890 sq.ft.", "Ahmedabad"],
      bg:'https://lh3.googleusercontent.com/p/AF1QipPXsyklzBdLFhPGUseSHT787gD_AEfrZpm0_5DK=s1360-w1360-h1020',
      locality:'Zundal, North West, Ahmedabad',
      area:'Zundal | Ready To Move ',
      bt1:'Apartment',
      bt2:'Buy',
      bt3:'Invest',
      images : [
        'https://lh3.googleusercontent.com/p/AF1QipOXCN4zWsuEsnZj1W9afr313bvpKwJZlXWPOoo6=s1360-w1360-h1020',
        'https://lh3.googleusercontent.com/p/AF1QipMAKNWnYvARNotlOttwF8vBo6Xffxv-9tWpl_vz=s1360-w1360-h1020',
        'https://lh3.googleusercontent.com/p/AF1QipMsYmsVDkhEATq-xWj0IiyleeRZqo3eB1aKEJ0_=s1360-w1360-h1020',
        'https://lh3.googleusercontent.com/p/AF1QipO2I_SnwMkdBjWp7HAmaV_6teg7w7OzC-pJvS7p=s1360-w1360-h1020',
      ],
      segment:"Affordable",
      address:'The Atlantis 2, Rhytham Heights, Nr Vivaan Infinity, B/h, Zundal, Ahmedabad, Gujarat 382421',
      bhk:"3 BHK",
      build:"1890 sq.ft.",
      price :'Price on Request',
      possession:'Ready To Move',
      nou:'168',    
      developer:'Satyagrah Developers',
      ptype:'Apartment',
      parea:'0.96 Acres',
      ownership:'Freehold',
      not:'3',
      nof:'14',
      parking:'Two Wheeler, Four Wheeler',
      overviewpara1:'The Atlantis 2 stands as a testament to the fusion of convenience and tranquility in real estate. Dedicated to offering prime locations coupled with serene surroundings, The Atlantis 2 guarantees seamless accessibility for every family member. With meticulous attention to detail, this property redefines the essence of opulent living.',
      overviewpara2:'From its strategic positioning to its thoughtful design, The Atlantis 2 prioritizes a comfortable commute and ensures that every aspect of daily life is effortlessly within reach. Whether its the convenience of nearby amenities or the promise of a peaceful environment, residents can expect a harmonious blend of convenience and luxury.',
      floorimg1:'https://houssed.com/Assets/Files/Projects/8172/Floor%20Plan/209a5c67a39a1f16bc1f110cd4b61373.webp',
      floordata:'',
      floorimg2:'',
      video:"https://www.youtube.com/embed/-Ozke0Ne08U?si=28-PH_OXEhF15Lze",
    },

    {
      id: 13,
      title: "Anantara Alora",
      subtitle: "Warm and Comfortable Living",
      category: "Residential",
      details: ["3 BHK", "2591-2681 sq.ft.", "Ahmedabad"],
      bg:'https://ashridhar.com/projects/anantara_alora/images/image/slider/anantara/Alora-Banner-2.png',
      locality:'Science Park, Ahmedabad 380059',
      area:'Science Park | Under Construction',
      bt1:'Apartment',
      bt2:'Buy',
      bt3:'Invest',
      images : [
        'https://ashridhar.com/projects/anantara_alora/images/image/slider/anantara/Alora-Banner-1.png',
        'https://ashridhar.com/projects/anantara_alora/images/image/slider/anantara/Alora-Banner-3.png',
        'https://ashridhar.com/projects/anantara_alora/images/image/slider/anantara/Alora-Banner-4.png',
        'https://housing-images.n7net.in/012c1500/c6ee897327c135e62af8d2d3e08c7a78/v0/fs.png',
      ],
      segment:"Luxury",
      address:'Science Park, Bhadaj, North West, Ahmedabad',
      bhk:"3 BHK",
      build:"2591-2681 sq.ft.",
      price :'Price on Request',
      possession:'Under Construction',
      nou:'104',    
      developer:'A Shridhar Group',
      ptype:'Apartment',
      parea:'1.5 Acres',
      ownership:'Freehold',
      not:'3',
      nof:'22',
      parking:'Two Wheeler, Four Wheeler',
      overviewpara1:"Bhadaj is well-connected to other parts of city by road, which passes through the heart of this suburb. Prominent shopping malls, movie theatres, school, and hospitals are present in proximity of this residential project.",
      overviewpara2:"A quiet and beautiful apartment located in heart of the city is available on sale in ahmadabad. Property is nicely located with all facilities nearby such as market, hospital, mother dairy, shopping mall, bus stand etc. Sector is very posh and premium",
      floorimg1:'https://c.housingcdn.com/demand/s/client/common/assets/requestFloorPlan.f9b9d5bc.jpg',
      floordata:'2591 Sq.ft.',
      floorimg2:'',
      video:"https://www.youtube.com/embed/Qe7h09wAVEc?si=Oen4fVdp1gB8HjR9"
    },
    
    {
      id: 14,
      title: "Rashmi Ombre",
      subtitle: "Luxury and Comfortable Living",
      category: "Residential",
      details: ["3,4 BHK", "2586-2645,3850 sq.ft.", "Ahmedabad"],
      bg:'https://rashmiengicon.com/wp-content/uploads/2024/12/Cam04_f-min-525x328.jpg?crop=1',
      locality:'Shantipura, South West, Ahmedabad',
      area:'Shantipura | Under Construction',
      bt1:'Apartment',
      bt2:'Buy',
      bt3:'Invest',
      images : [
        'https://rashmiengicon.com/wp-content/uploads/2024/12/Cam02_f-min-525x328.jpg?crop=1',
        'https://rashmiengicon.com/wp-content/uploads/2024/12/Cam13_f-min-525x328.jpg?crop=1',
        'https://rashmiengicon.com/wp-content/uploads/2024/12/Ombre_Living-2-min-525x328.jpg?crop=1',
        'https://rashmiengicon.com/wp-content/uploads/2024/12/Cam08_f-min-525x328.jpg?crop=1',
        'https://rashmiengicon.com/wp-content/uploads/2024/12/Cam15_F-min-525x328.jpg?crop=1'
      ],
      segment:"Luxury",
      address:'Link-in Road, Shantipura, South West, Ahmedabad',
      bhk:"3,4 BHK",
      build:"2586-2645,3850 sq.ft.",
      price :'Price on Request',
      possession:'Under Construction',
      nou:'164',    
      developer:'Rashmi Group',
      ptype:'Apartment',
      parea:'1.58 Acres',
      ownership:'Freehold',
      not:'3',
      nof:'14',
      parking:'Two Wheeler, Four Wheeler',
      overviewpara1:"Elevate your lifestyle in a space where modern design meets unparalleled elegance, providing a harmonious balance between urban living and serenity. Welcome to a residence where every detail is meticulously crafted to enhance your living experience.",
      overviewpara2:"",
      floorimg1:'https://housing-images.n7net.in/91aba65c/82be38e738d6629320298411442cd1c6/v0/fs.jpeg',
      floordata:'3,4 BHK',
      floorimg2:'https://housing-images.n7net.in/91aba65c/82be38e738d6629320298411442cd1c6/v0/fs.jpeg',
      video:"https://www.youtube.com/embed/Qe7h09wAVEc?si=Oen4fVdp1gB8HjR9"
    },

    {
      id: 15,
      title: "Vertis",
      subtitle: "Modern Urban Living",
      category: "Residential",
      details: ["3,4 BHK", "2586-2645,3850 sq.ft.", "Ahmedabad"],
      bg:'https://rashmiengicon.com/wp-content/uploads/2024/12/Cam04_f-min-525x328.jpg?crop=1',
      locality:'Shantipura, South West, Ahmedabad',
      area:'Shantipura | Under Construction',
      bt1:'Apartment',
      bt2:'Buy',
      bt3:'Invest',
      images : [
        'https://rashmiengicon.com/wp-content/uploads/2024/12/Cam02_f-min-525x328.jpg?crop=1',
        'https://rashmiengicon.com/wp-content/uploads/2024/12/Cam13_f-min-525x328.jpg?crop=1',
        'https://rashmiengicon.com/wp-content/uploads/2024/12/Ombre_Living-2-min-525x328.jpg?crop=1',
        'https://rashmiengicon.com/wp-content/uploads/2024/12/Cam08_f-min-525x328.jpg?crop=1',
        'https://rashmiengicon.com/wp-content/uploads/2024/12/Cam15_F-min-525x328.jpg?crop=1'
      ],
      segment:"Luxury",
      address:'Link-in Road, Shantipura, South West, Ahmedabad',
      bhk:"3,4 BHK",
      build:"2586-2645,3850 sq.ft.",
      price :'Price on Request',
      possession:'Under Construction',
      nou:'164',    
      developer:'Rashmi Group',
      ptype:'Apartment',
      parea:'1.58 Acres',
      ownership:'Freehold',
      not:'3',
      nof:'14',
      parking:'Two Wheeler, Four Wheeler',
      overviewpara1:"Elevate your lifestyle in a space where modern design meets unparalleled elegance, providing a harmonious balance between urban living and serenity. Welcome to a residence where every detail is meticulously crafted to enhance your living experience.",
      overviewpara2:"",
      floorimg1:'https://housing-images.n7net.in/91aba65c/82be38e738d6629320298411442cd1c6/v0/fs.jpeg',
      floordata:'3,4 BHK',
      floorimg2:'https://housing-images.n7net.in/91aba65c/82be38e738d6629320298411442cd1c6/v0/fs.jpeg',
      video:"https://www.youtube.com/embed/Qe7h09wAVEc?si=Oen4fVdp1gB8HjR9"
    },

  
  ];
  
  const commercialProjects = [
  {
      id: 1,
      title: "Z2",
      subtitle: "Sky Scraper Building",
      category: "Commercial",
      details: ["32 Stories", "1230-10000 sq.ft.", "Thaltej"],
      bg:'https://img.staticmb.com/mbimages/project/2024/08/21/Project-Photo-5-Z2-Ahmedabad-5415119_926_1600.jpg',
      locality:'Zydus Road, Thaltej, Ahmedabad',
      area:'Thaltej | Under Construction',
      bt1:'Commercial',
      bt2:'Buy',
      bt3:'Invest',
      images : [
        'https://img.staticmb.com/mbimages/project/2024/08/21/Project-Photo-2-Z2-Ahmedabad-5415119_1893_1600.jpg',
        'https://img.staticmb.com/mbimages/project/2024/08/21/Project-Photo-7-Z2-Ahmedabad-5415119_1917_1600.jpg',
        'https://img.staticmb.com/mbimages/project/2024/08/21/Project-Photo-4-Z2-Ahmedabad-5415119_1102_1600.jpg',
        'https://img.staticmb.com/mbimages/project/2024/08/21/Project-Photo-6-Z2-Ahmedabad-5415119_934_1600.jpg',
        'https://img.staticmb.com/mbimages/project/2024/08/21/Project-Photo-8-Z2-Ahmedabad-5415119_2000_1333.jpg'
      ],
      segment:"Luxury",
      address:'Zydus Road, Thaltej, Ahmedabad, 380058',
      bhk:"",
      build:"1230-10000 sq.ft.",
      price :'Price on Request',
      possession:'Under Construction',
      nou:'155',    
      developer:' Zade Infraspace LLP',
      ptype:'Commerical Space',
      parea:'2984 Sq-m',
      ownership:'Freehold',
      not:'1',
      nof:'32',
      parking:'Two Wheeler, Four Wheeler',
      overviewpara1:"Z2 offers a premium business destination with its modern offices and showrooms in Thaltej, Ahmedabad. Designed with contemporary architecture and spacious layouts, Z2 caters to the diverse needs of businesses, providing a professional and sophisticated environment.",
      overviewpara2:"Located in the bustling Thaltej area, these commercial spaces ensure excellent connectivity to major city hubs and high visibility, making it the perfect location for businesses seeking growth and success. Whether for corporate offices or showrooms, Z2 offers an ideal platform for businesses to thrive in one of Ahmedabad’s prime commercial locations",
       floorimg1:'https://img.staticmb.com/mbimages/project/2024/08/21/Floor-Plan-10-Z2-Ahmedabad-5415119_1113_1600.jpg',
       floordata:'1-19 Stroies Plan',
       floorimg2:'https://img.staticmb.com/mbimages/project/2024/08/21/Master-Plan-11-Z2-Ahmedabad-5415119_1332_1600.jpg',
      video:"https://www.youtube.com/embed/8UH-tTWELZc?si=5CJI9erKGNUVf9Aw" 
  },

  {
          id: 2,
          title: "The Orion",
          subtitle: "Premium Office Buildings",
          category: "Commercial",
          details: ["13 Stories", "1166-3100 Sq.ft Office", "Thaltej"],
          bg:'',
          locality:'Charodi, SG Highway, Ahmedabad',
          area:'SG Highway | Under Construction',
          bt1:'1-3 Showroom, 4-13 Office Space',
          bt2:'Buy',
          bt3:'Invest',
          images : [
            '',
            '',
            '',
            '',
            ''
          ],
          segment:"Premium",
          address:' Sarkhej - Gandhinagar Hwy, near Shree Balaji Temple, Ahmedabad',
          bhk:"",
          build:"1166-3100 Sq.ft Office",
          price :'Price on Request',
          possession:'Under Construction',
          nou:'128',    
          developer:'HARI HARAY INFRASPACE',
          ptype:'Commerical Space',
          parea:'3246 Sq.yard',
          ownership:'Freehold',
          not:'1',
          nof:'13',
          parking:'Two Wheeler, Four Wheeler',
          overviewpara1:"Situated in Sarkhej Gandhinagar Highway, the The Orion is planned to offer a modern lifestyle to all the residents. The property features various unit types as Commercial Office Space, which are constructed to offer complete satisfaction. The Orion project is an offering from the well-established developer HARI HARAY INFRASPACE. Its pincode is 380060. Enjoy the comforts of living in The Orion with all modern conveniences at your disposal.",
          overviewpara2:"",
          floorimg1:'',
          floordata:'',
          floorimg2:'',
          video:"" 
  },

    
  {
        id: 3,
        title: "Trogon Twin Towers",
        subtitle: "Premium Commercial Spaces",
        category: "Commercial",
        details: ["G+32 Floors", "928-17100 Sq.ft Office", "SG Highway"],
        bg: 'https://pbs.twimg.com/media/F7uolPjbIAAvZp_.jpg:large',
        locality: 'SG Highway, Ahmedabad',
        area: 'SG Highway | Under Construction',
        bt1: '1-4 Showroom, 6-32 Office Space',
        bt2: 'Buy',
        bt3: 'Invest',
        images: [
          'https://www.shelter4u.in/mask/uploads/property/main_photo/96353_97374_40324.jpg',
          'https://growedgerealty.com/project_images/662265074bb1f.jpg',
          'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200_webp/9526e2181572577.651e402d93990.png',
          'https://growedgerealty.com/project_images/6622650751099.jpg',
          'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/b1e806181572577.651e402d971bb.png'
        ],
        segment: "Premium",
        address: 'SG Highway, Ahmedabad',
        bhk: "",
        build: "928-17100 Sq.ft Office",
        price: 'Price on Request',
        possession: 'Under Construction',
        nou: '', 
        developer: 'Trogon Group',
        ptype: 'Commercial Space',
        parea: '3.4 Acres', 
        ownership: 'Freehold',
        not: '2',
        nof: '33', 
        parking: 'Two Wheeler, Four Wheeler',
        overviewpara1: "Located on SG Highway, the Iconic Tower by Trogon Group is a landmark commercial destination featuring a blend of showrooms and premium office spaces. The project includes a 4-level basement for parking and utilities, Ground + 32 floors of high-end commercial infrastructure.",
        overviewpara2: "Iconic Tower offers excellent connectivity, premium amenities, and modern architectural design, making it a perfect destination for businesses looking to establish a prestigious address in Ahmedabad.",
        floorimg1: 'https://img.staticmb.com/mbimages/project/2024/07/08/Floor-Plan-20-Trogon-Twin-Towers-Ahmedabad-5416915_386_539.jpg',
        floordata: 'Floor Plan & Master Plan',
        floorimg2: 'https://img.staticmb.com/mbimages/project/2024/07/08/Master-Plan-23-Trogon-Twin-Towers-Ahmedabad-5416915_398_543.jpg',
        video: "https://www.youtube.com/embed/6HMF_LHDUyU?si=au7sTfzmDEZXL4qA",
        
  },
    
  {
      id: 4,
      title: "The Opus By Shankus & Aristo ",
      subtitle: "Premium Commercial Spaces",
      category: "Commercial",
      details: ["G+32 Floors", "1000-2000 Sq.ft Office", "SG Highway"],
      bg: '',
      locality: 'SG Highway, Ahmedabad',
      area: 'SG Highway | Under Construction',
      bt1: '1-4 Showroom, 5-32 Office Space',
      bt2: 'Buy',
      bt3: 'Invest',
      images: [
        '',
        '',
        '',
        '',
        ''
      ],
      segment: "Premium",
      address: 'SG Highway, Ahmedabad',
      bhk: "",
      build: "1000-2000 Sq.ft Office",
      price: 'Price on Request',
      possession: 'Under Construction',
      nou: '', 
      developer: 'Aristo Group',
      ptype: 'Commercial Space',
      parea: '', 
      ownership: 'Freehold',
      not: '1',
      nof: '33', 
      parking: 'Two Wheeler, Four Wheeler',
      overviewpara1: "Shankush Tower by Arista Group is an iconic commercial tower situated on SG Highway, Ahmedabad. Designed to meet the demands of modern businesses, the tower features 4 basement levels and G+32 floors. The first four floors are dedicated to showrooms, while the 5th to 32nd floors offer intelligently planned office spaces ranging from 1000 to 2000 sq.ft.",
      overviewpara2: "With contemporary amenities, flexible office layouts, and strategic location, Shankush Tower is an ideal business address. Attractive DP and Regular pricing options are available along with comprehensive maintenance and infrastructure facilities.",
      floorimg1: '',
      floordata: '',
      floorimg2: '',
      video: "",
      
  },

  {
    id: 5,
    title: "Brillia",
    subtitle: "Modern Commercial Tower",
    category: "Commercial",
    details: ["G+32 Floors", "1300 - 8665 sq.ft Offices", "SG Highway"],
    bg: 'https://brilliapravish.com/_next/image?url=%2Fassets%2Fimages%2Fimage8.jpg&w=750&q=75',
    locality: 'SG Highway, Ahmedabad',
    area: 'SG Highway | Under Construction',
    bt1: '1-3 Showroom, 4-32 Office Space',
    bt2: 'Buy',
    bt3: 'Invest',
    images: [
      'https://brilliapravish.com/_next/image?url=%2Fassets%2Fimages%2FcontactForm.png&w=1200&q=75',
      'https://brilliapravish.com/_next/image?url=%2Fassets%2Fimages%2Fimage6.jpg&w=750&q=75',
      'https://brilliapravish.com/_next/image?url=%2Fassets%2Fimages%2FImage1.jpg&w=750&q=75',
      'https://brilliapravish.com/assets/images/brilliaHome3.jpg',
      'https://brilliapravish.com/_next/image?url=%2Fassets%2Fimages%2Fimage8.jpg&w=750&q=75'
    ],
    segment: "Premium",
    address: 'SG Highway, Ahmedabad',
    bhk: "",
    build: "1300 - 8665 sq.ft",
    price: 'Price on Request',
    possession: 'Under Construction',
    nou: '481', 
    developer: 'Acorn Realities',
    ptype: 'Commercial Space',
    parea: '', 
    ownership: 'Freehold',
    not: '1',
    nof: '33', 
    parking: 'Two Wheeler, Four Wheeler',
    overviewpara1: "Iconic Tower by Parwesh Group stands as a symbol of architectural brilliance on SG Highway. This G+32 floor commercial structure includes 4 levels of basement parking. The first 3 floors are allocated for showrooms, and floors 4 to 32 are for spacious office units — with the 20th floor intentionally skipped for design and structure.",
    overviewpara2: "Offering office spaces ranging from 1308 to 35000 sq.ft, Iconic Tower is ideal for businesses of all sizes. The project comes with competitive pricing options, a floor level charge after the 15th floor, and all essential amenities required for a premium commercial environment.",
    floorimg1: 'https://prelaunchoffers.com/wp-content/uploads/2024/04/First-Floor-Plan.jpg',
    floordata: '',
    floorimg2: 'https://prelaunchoffers.com/wp-content/uploads/2024/04/30th-and-31st-Floor-Plan.jpg',
    video: "https://www.youtube.com/embed/5kJtuKnQaPo?si=4w70zKiK9I-V5_MS",
    
  },


  {
    id: 6,
    title: "The Citadel",
    subtitle: "SkyScraper Commercial Tower",
    category: "Commercial",
    details: ["19 Floors", "1,100 Sq.ft. Offices", "SG Highway"],
    bg: 'https://img.staticmb.com/mbimages/project/2024/11/14/Project-Photo-1-The-Citadel-Ahmedabad-5424631_410_1440.jpg',
    locality: 'Iscon Ambli Road, Ahmedabad',
    area: 'SG Highway | Under Construction',
    bt1: 'G+1 Showroom, 2-19 Office Space',
    bt2: 'Buy',
    bt3: 'Invest',
    images: [
      'https://img.staticmb.com/mbimages/project/2024/11/14/Project-Photo-9-The-Citadel-Ahmedabad-5424631_1276_1000.jpg',
      'https://img.staticmb.com/mbimages/project/2024/11/14/Project-Photo-10-The-Citadel-Ahmedabad-5424631_1280_1280.jpg',
      'https://img.staticmb.com/mbimages/project/2024/11/14/Project-Photo-8-The-Citadel-Ahmedabad-5424631_964_1280.jpg',
      'https://img.staticmb.com/mbimages/project/2024/11/14/Project-Photo-12-The-Citadel-Ahmedabad-5424631_960_1280.jpg',
      'https://img.staticmb.com/mbimages/project/2024/11/14/Project-Photo-14-The-Citadel-Ahmedabad-5424631_720_1280.jpg',
      'https://img.staticmb.com/mbimages/project/2024/11/14/Project-Photo-15-The-Citadel-Ahmedabad-5424631_720_1280.jpg',
      'https://img.staticmb.com/mbimages/project/2024/11/14/Project-Photo-18-The-Citadel-Ahmedabad-5424631_720_1280.jpg'
    ],
    segment: "Premium",
    address: 'SG Highway, Ahmedabad',
    bhk: "",
    build: "1,100 Sq.ft. Offices",
    price: 'Price on Request',
    possession: 'Under Construction',
    nou: '', 
    developer: 'Shivam Group',
    ptype: 'Commercial Space',
    parea: '', 
    ownership: 'Freehold',
    not: '1',
    nof: '19', 
    parking: 'Two Wheeler, Four Wheeler',
    overviewpara1: "The Citadel by Shivam Group is a premium commercial development strategically located on SG Highway, one of Ahmedabad’s most bought-after commercial zones. This 19-floor skyscraper is designed to offer state-of-the-art office spaces starting from 1,100 sq.ft., catering to modern businesses that demand both functionality and prestige. The lower levels feature G+1 showrooms, ensuring high visibility and easy customer access, while upper floors are dedicated to well-planned office units.", 
  overviewpara2: "With its iconic architecture and prime location, The Citadel is set to become a landmark business address. The project offers robust infrastructure, contemporary amenities, and excellent connectivity to key parts of the city. Whether you're looking to invest or establish your business in a thriving commercial corridor, The Citadel delivers on both potential and performance.",
    floorimg1: '',
    floordata: '',
    floorimg2: '',
    video: "",
    
  },
  

  ];
  
  
  
  const plotProjects = [
    {
      id: 1,
      title: "Suburban Plot",
      subtitle: "Perfect for Villas",
      image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80",
      category: "Plots",
      details: ["Plot", "2500 sqft", "Suburbia"],
    },
    {
      id: 2,
      title: "City View Plot",
      subtitle: "Ideal for Residential Buildings",
      image: "https://images.unsplash.com/photo-1506150194731-e3f392f8d52b?auto=format&fit=crop&q=80",
      category: "Plots",
      details: ["Plot", "3500 sqft", "City Center"],
    },
    {
      id: 3,
      title: "Mountain View Plot",
      subtitle: "Perfect for Summer Homes",
      image: "https://images.unsplash.com/photo-1518290193666-56de63c0d48b?auto=format&fit=crop&q=80",
      category: "Plots",
      details: ["Plot", "4000 sqft", "Mountain Side"],
    },
    {
      id: 4,
      title: "Coastal Plot",
      subtitle: "Beachfront Development Opportunity",
      image: "https://images.unsplash.com/photo-1555285736-cfe4a31abf63?auto=format&fit=crop&q=80",
      category: "Plots",
      details: ["Plot", "5000 sqft", "Seaside"],
    },
    {
      id: 5,
      title: "Urban Residential Plot",
      subtitle: "Close to Amenities",
      image: "https://images.unsplash.com/photo-1529208220849-7249a29f77db?auto=format&fit=crop&q=80",
      category: "Plots",
      details: ["Plot", "3000 sqft", "Urban Area"],
    },
    {
      id: 6,
      title: "Green Acres",
      subtitle: "Ideal for Eco-friendly Homes",
      image: "https://images.unsplash.com/photo-1567405299-0da5a1e503bc?auto=format&fit=crop&q=80",
      category: "Plots",
      details: ["Plot", "6000 sqft", "Greenbelt"],
    },
    {
      id: 7,
      title: "Prime Commercial Plot",
      subtitle: "Strategic Location for Businesses",
      image: "https://images.unsplash.com/photo-1535683561310-73a507fba537?auto=format&fit=crop&q=80",
      category: "Plots",
      details: ["Plot", "7000 sqft", "Business Hub"],
    },
    {
      id: 8,
      title: "Vibrant Neighborhood Plot",
      subtitle: "For Modern Housing",
      image: "https://images.unsplash.com/photo-1570145208083-bdd2a5f88b30?auto=format&fit=crop&q=80",
      category: "Plots",
      details: ["Plot", "5500 sqft", "Vibrant Area"],
    },
 
  ];
  

  const industrialProjects = [
    {
      id: 1,
      title: "Industrial Park",
      subtitle: "For Manufacturing Units",
      image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80",
      category: "Industrial",
      details: ["Factory Spaces", "10000 sqft", "Industrial Area"],
    },
    {
      id: 2,
      title: "Tech Manufacturing Hub",
      subtitle: "State-of-the-art Industrial Spaces",
      image: "https://images.unsplash.com/photo-1581005195875-1f57bfcba04a?auto=format&fit=crop&q=80",
      category: "Industrial",
      details: ["Manufacturing Units", "15000 sqft", "Tech District"],
    },
    {
      id: 3,
      title: "Logistics Center",
      subtitle: "Distribution and Warehousing Spaces",
      image: "https://images.unsplash.com/photo-1580587769992-d980157597f7?auto=format&fit=crop&q=80",
      category: "Industrial",
      details: ["Warehouses", "20000 sqft", "Logistics Zone"],
    },
    {
      id: 4,
      title: "Advanced Factory Space",
      subtitle: "Modern Facilities for Production",
      image: "https://images.unsplash.com/photo-1601015676342-c5dbeb6c5d1f?auto=format&fit=crop&q=80",
      category: "Industrial",
      details: ["Production Units", "25000 sqft", "Manufacturing District"],
    },
    {
      id: 5,
      title: "Heavy Industrial Units",
      subtitle: "For Large Scale Manufacturing",
      image: "https://images.unsplash.com/photo-1531164733484-83163d8f100b?auto=format&fit=crop&q=80",
      category: "Industrial",
      details: ["Industrial Units", "30000 sqft", "Heavy Industry Area"],
    },
    {
      id: 6,
      title: "Automotive Production Park",
      subtitle: "Dedicated to Automotive Manufacturing",
      image: "https://images.unsplash.com/photo-1589307423030-e17613c55172?auto=format&fit=crop&q=80",
      category: "Industrial",
      details: ["Manufacturing Units", "35000 sqft", "Automotive Hub"],
    },
    {
      id: 7,
      title: "Green Energy Facility",
      subtitle: "For Renewable Energy Production",
      image: "https://images.unsplash.com/photo-1594721944589-d11b16b65c8b?auto=format&fit=crop&q=80",
      category: "Industrial",
      details: ["Energy Units", "18000 sqft", "Renewable Energy Zone"],
    },
    {
      id: 8,
      title: "Cold Storage Complex",
      subtitle: "Temperature-controlled Warehouse",
      image: "https://images.unsplash.com/photo-1591345427589-11e37488a59c?auto=format&fit=crop&q=80",
      category: "Industrial",
      details: ["Cold Storage", "22000 sqft", "Industrial Park"],
    },
  
   
  ];
  
  
  export { residentialProjects, commercialProjects, plotProjects, industrialProjects };
  